saferam1	=appbackupscreen
saferam2	=statvars
grbuf		=plotsscreen
graph_mem	=plotsscreen
gbuf		=plotsscreen
sram		=saferam1
apdram		=saferam1
statram		=saferam2
vat		=progptr
saferam5	=imathptr1
;-----> Ion Functions
lVectors	=cmdshadow+80
ionVersion	=lVectors
ionRandom	=lVectors+3
ionPutSprite	=lVectors+6
ionLargeSprite	=lVectors+9
ionGetPixel	=lVectors+12
ionFastCopy	=lVectors+15
ionDetect	=lVectors+18
ionDecompress	=lVectors+21


